### ISSUE TITLE
what is this? hxsg for HTML???  0v0

### ISSUE THREAD

**Issue by akina2022** [ychunc/hxsg#4]

**Comment by ychunc** [comment]
yeah! use typescript

**Comment by akina2022** [comment]
> yeah! use typescript

Oh，It is amazing，Looking forward to you doing  it better.

**Comment by ychunc** [comment]
I'm sorry. I don't have time to do it now

**Comment by akina2022** [comment]
> I'm sorry. I don't have time to do it now

oh haah,it is no matter.
![Uploading 640.gif…]()

**Comment by akina2022** [comment]
![640](https://github.com/user-attachments/assets/893ee916-8edb-4b9e-8884-b0ccc25d4cf1)
oh haah,it is no matter.
